# Generated by Django 4.1.3 on 2023-03-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycalendar", "0002_department_leaverequest_department_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="leave_bal",
            field=models.IntegerField(default="0", null=True),
        ),
    ]
