# Generated by Django 4.2.1 on 2023-06-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0004_leaverequest_leave_ent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_ent',
            field=models.IntegerField(unique=True),
        ),
    ]
